name: "Check"
on: # yamllint disable rule:truthy
  pull_request:
  push:
    branches: [main]

jobs:
  flake-check:
    runs-on: ubuntu-latest
    # cancel previous runs when pushing new changes
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: "system-features = kvm nixos-test"
      - run: nix flake check -L
